"""
Script to programmatically create the 07_inspect_feature_selection.ipynb notebook
using nbformat, then save it ready for execution.
"""

import nbformat
from nbformat.v4 import new_notebook, new_code_cell, new_markdown_cell
import os

cells = []

# ── Cell 0: Setup & imports ──────────────────────────────────────────────────
cells.append(new_code_cell(
    "import sys, os\n"
    "import json\n"
    "import re\n"
    "import warnings\n"
    "warnings.filterwarnings('ignore')\n"
    "\n"
    "PROJECT_ROOT = os.path.abspath('..')\n"
    "if PROJECT_ROOT not in sys.path:\n"
    "    sys.path.insert(0, PROJECT_ROOT)\n"
    "\n"
    "import numpy as np\n"
    "import pandas as pd\n"
    "import matplotlib\n"
    "matplotlib.use('Agg')\n"
    "import matplotlib.pyplot as plt\n"
    "import seaborn as sns\n"
    "from sklearn.model_selection import train_test_split\n"
    "from sklearn.linear_model import LogisticRegression\n"
    "from sklearn.metrics import f1_score\n"
    "\n"
    "from src.utils.safe_loader import safe_load_npy\n"
    "from src.training.scaler import FeatureScaler\n"
    "from src.training.feature_selection import (\n"
    "    get_feature_names, \n"
    "    run_feature_selection, \n"
    "    save_selected_features,\n"
    "    get_logistic_regression\n"
    ")\n"
    "\n"
    "FIGURES_DIR = 'figures'\n"
    "os.makedirs(FIGURES_DIR, exist_ok=True)\n"
    "\n"
    "PHASE_DIR = os.path.join(\n"
    "    PROJECT_ROOT,\n"
    "    '.planning', 'phases', '03-dataset-standardization-mrmr-selection'\n"
    ")\n"
    "\n"
    "print('Setup complete.')\n"
    "print(f'Project root: {PROJECT_ROOT}')\n"
    "print(f'CWD: {os.getcwd()}')\n"
))

# ── Cell 1: Read DECISION.md to get winning scaler ────────────────────────────
cells.append(new_markdown_cell("## Extract Winning Scaler from DECISION.md"))

cells.append(new_code_cell(
    "decision_md_path = os.path.join(PHASE_DIR, 'DECISION.md')\n"
    "with open(decision_md_path, 'r') as fh:\n"
    "    content = fh.read()\n"
    "\n"
    "match = re.search(r'\\*\\*Final choice:\\*\\* `([^`]+)`', content)\n"
    "if match:\n"
    "    winning_scaler = match.group(1)\n"
    "else:\n"
    "    winning_scaler = 'RobustScaler'\n"
    "\n"
    "print(f'Extracted winning scaler: {winning_scaler}')\n"
))

# ── Cell 2: Load data and apply scaler ────────────────────────────────────────
cells.append(new_markdown_cell("## Section 1 — Setup & Scaled Data Loading"))

cells.append(new_code_cell(
    "X_PATH = os.path.join(PROJECT_ROOT, 'data', 'processed', 'fold1_binary_X.npy')\n"
    "Y_PATH = os.path.join(PROJECT_ROOT, 'data', 'processed', 'fold1_binary_y.npy')\n"
    "\n"
    "print('Loading raw feature matrix (mmap, read-only)...')\n"
    "X_mm = safe_load_npy(X_PATH, mode='r')\n"
    "y_mm = safe_load_npy(Y_PATH, mode='r')\n"
    "\n"
    "print(f'X shape: {X_mm.shape}, y shape: {y_mm.shape}')\n"
    "\n"
    "SAMPLE_N = 100_000\n"
    "RANDOM_STATE = 42\n"
    "\n"
    "print(f'Drawing stratified subsample of {SAMPLE_N:,} rows...')\n"
    "_, sub_idx = train_test_split(\n"
    "    np.arange(len(y_mm)),\n"
    "    test_size=SAMPLE_N,\n"
    "    stratify=np.array(y_mm),\n"
    "    random_state=RANDOM_STATE,\n"
    ")\n"
    "sub_idx = np.sort(sub_idx)\n"
    "X_sub = np.array(X_mm[sub_idx], dtype=np.float32)\n"
    "y_sub = np.array(y_mm[sub_idx], dtype=np.int32)\n"
    "X_sub = np.nan_to_num(X_sub, nan=0.0, posinf=0.0, neginf=0.0)\n"
    "\n"
    "print('Fitting extracted scaler and transforming subsample...')\n"
    "fs = FeatureScaler(scaler_type=winning_scaler)\n"
    "fs._scaler.fit(X_sub)\n"
    "X_scaled = fs._scaler.transform(X_sub).astype(np.float32)\n"
    "X_scaled = np.nan_to_num(X_scaled, nan=0.0, posinf=0.0, neginf=0.0)\n"
    "\n"
    "# Split 80k train / 20k validation\n"
    "X_tr, X_val, y_tr, y_val = train_test_split(\n"
    "    X_scaled, y_sub, test_size=0.2, stratify=y_sub, random_state=RANDOM_STATE\n"
    ")\n"
    "\n"
    "print(f'Train shape: {X_tr.shape}, Val shape: {X_val.shape}')\n"
    "classes, counts = np.unique(y_tr, return_counts=True)\n"
    "print('Train class distribution:')\n"
    "for c, n in zip(classes, counts):\n"
    "    print(f'  class {c}: {n:,}  ({n/len(y_tr)*100:.1f}%)')\n"
))

# ── Cell 3: N-Sweep ──────────────────────────────────────────────────────────
cells.append(new_markdown_cell("## Section 2 — N-Sweep: F1 vs Feature Count"))

cells.append(new_code_cell(
    "N_VALUES = [10, 15, 20, 25, 30]\n"
    "METHODS = ['mrmr', 'anova', 'rfe']\n"
    "\n"
    "sweep_results = []\n"
    "feature_selections = {}  # Store selected indices for correlation/Jaccard\n"
    "\n"
    "for method in METHODS:\n"
    "    feature_selections[method] = {}\n"
    "    for n in N_VALUES:\n"
    "        print(f'Running selection: method={method}, n={n}...')\n"
    "        indices, names = run_feature_selection(X_tr, y_tr, n_features=n, method=method)\n"
    "        feature_selections[method][n] = (indices, names)\n"
    "        \n"
    "        # Train proxy model\n"
    "        lr = get_logistic_regression(max_iter=500, random_state=RANDOM_STATE)\n"
    "        lr.fit(X_tr[:, indices], y_tr)\n"
    "        y_pred = lr.predict(X_val[:, indices])\n"
    "        f1 = float(f1_score(y_val, y_pred, average='macro'))\n"
    "        \n"
    "        sweep_results.append({\n"
    "            'method': method,\n"
    "            'n': n,\n"
    "            'macro_f1': f1\n"
    "        })\n"
    "        print(f'  -> F1: {f1:.4f}')\n"
    "\n"
    "# Fit full 93 features baseline\n"
    "print('Running full 93 features baseline...')\n"
    "lr_full = get_logistic_regression(max_iter=500, random_state=RANDOM_STATE)\n"
    "lr_full.fit(X_tr, y_tr)\n"
    "y_pred_full = lr_full.predict(X_val)\n"
    "baseline_f1 = float(f1_score(y_val, y_pred_full, average='macro'))\n"
    "print(f'Baseline F1 (93 features): {baseline_f1:.4f}')\n"
    "\n"
    "df_sweep = pd.DataFrame(sweep_results)\n"
    "df_pivot = df_sweep.pivot(index='n', columns='method', values='macro_f1')\n"
    "print('\\nSweep Results Table:')\n"
    "print(df_pivot.to_string())\n"
))

# ── Cell 4: Elbow Rule Application ───────────────────────────────────────────
cells.append(new_markdown_cell("## Section 4 — Elbow Rule Application"))

cells.append(new_code_cell(
    "# Elbow point logic: smallest n where delta_f1 < 0.002\n"
    "ELBOW_THRESHOLD = 0.002\n"
    "deltas = []\n"
    "\n"
    "for method in METHODS:\n"
    "    method_rows = df_sweep[df_sweep['method'] == method].sort_values('n')\n"
    "    f1_list = method_rows['macro_f1'].tolist()\n"
    "    n_list = method_rows['n'].tolist()\n"
    "    \n"
    "    # n=10 has no delta\n"
    "    deltas.append({'method': method, 'n': 10, 'macro_f1': f1_list[0], 'delta_f1': 0.0})\n"
    "    \n"
    "    for idx in range(1, len(f1_list)):\n"
    "        delta = f1_list[idx] - f1_list[idx-1]\n"
    "        deltas.append({\n"
    "            'method': method,\n"
    "            'n': n_list[idx],\n"
    "            'macro_f1': f1_list[idx],\n"
    "            'delta_f1': delta\n"
    "        })\n"
    "\n"
    "df_deltas = pd.DataFrame(deltas)\n"
    "print('Deltas Table:')\n"
    "print(df_deltas.to_string(index=False))\n"
    "\n"
    "# Find elbow point for each method\n"
    "elbow_points = {}\n"
    "for method in METHODS:\n"
    "    m_deltas = df_deltas[df_deltas['method'] == method].sort_values('n')\n"
    "    chosen_n = 20  # Default if no elbow is found\n"
    "    # Scan from n=15 upwards\n"
    "    for _, row in m_deltas.iterrows():\n"
    "        if row['n'] == 10:\n"
    "            continue\n"
    "        if row['delta_f1'] < ELBOW_THRESHOLD:\n"
    "            # This is the first n where improvement is below threshold\n"
    "            # So we choose the *previous* n, or this n? The rule says:\n"
    "            # \"smallest n where the marginal F1 gain from adding the next 5 features drops below 0.002\"\n"
    "            # This means adding features beyond this n yields marginal returns < 0.002.\n"
    "            # So we stop at this row's previous n, or this row's n itself as the point where the elbow occurred.\n"
    "            # Let's select the row's n itself as the elbow feature count.\n"
    "            chosen_n = int(row['n'])\n"
    "            break\n"
    "    elbow_points[method] = chosen_n\n"
    "\n"
    "print('\\nElbow points identified:')\n"
    "for method, en in elbow_points.items():\n"
    "    print(f'  {method}: n={en}')\n"
    "\n"
    "# We will choose the overall winner method based on F1 at their respective elbow points\n"
    "best_score = -1\n"
    "best_method = None\n"
    "best_n = None\n"
    "\n"
    "for method, en in elbow_points.items():\n"
    "    score = df_sweep[(df_sweep['method'] == method) & (df_sweep['n'] == en)]['macro_f1'].values[0]\n"
    "    if score > best_score:\n"
    "        best_score = score\n"
    "        best_method = method\n"
    "        best_n = en\n"
    "\n"
    "print(f'\\nELBOW RESULT: winner_method={best_method}, chosen_n={best_n}, validation_macro_f1={best_score:.4f}')\n"
))

# ── Cell 5: Elbow Plot ───────────────────────────────────────────────────────
cells.append(new_markdown_cell("## Section 3 — Elbow Plot (F1 vs n)"))

cells.append(new_code_cell(
    "plt.figure(figsize=(10, 6))\n"
    "for method in METHODS:\n"
    "    m_rows = df_sweep[df_sweep['method'] == method].sort_values('n')\n"
    "    plt.plot(m_rows['n'], m_rows['macro_f1'], marker='o', label=method.upper(), linewidth=2)\n"
    "    # Draw dashed line at this method's elbow point\n"
    "    plt.axvline(x=elbow_points[method], linestyle='--', alpha=0.5, label=f'{method.upper()} elbow (n={elbow_points[method]})')\n"
    "\n"
    "plt.axhline(y=baseline_f1, color='grey', linestyle=':', label=f'Full Baseline (n=93, F1={baseline_f1:.4f})', alpha=0.8)\n"
    "\n"
    "plt.title('Feature Count vs Proxy Macro-F1 — Elbow Analysis', fontsize=12)\n"
    "plt.xlabel('Number of Features (n)', fontsize=10)\n"
    "plt.ylabel('Proxy Model Validation Macro-F1', fontsize=10)\n"
    "plt.xticks(N_VALUES)\n"
    "plt.grid(True, linestyle=':', alpha=0.6)\n"
    "plt.legend(loc='lower right', fontsize=8)\n"
    "\n"
    "plot_path = os.path.join(FIGURES_DIR, '07_f1_elbow.png')\n"
    "plt.savefig(plot_path, dpi=120, bbox_inches='tight')\n"
    "plt.close()\n"
    "print(f'Elbow plot saved -> {plot_path}')\n"
))

# ── Cell 6: Jaccard Overlap Heatmap ──────────────────────────────────────────
cells.append(new_markdown_cell("## Section 5 — Jaccard Overlap Heatmap"))

cells.append(new_code_cell(
    "jaccard_matrix = np.zeros((len(METHODS), len(METHODS)))\n"
    "\n"
    "for i, m1 in enumerate(METHODS):\n"
    "    idx1 = set(feature_selections[m1][best_n][0])\n"
    "    for j, m2 in enumerate(METHODS):\n"
    "        idx2 = set(feature_selections[m2][best_n][0])\n"
    "        intersection = len(idx1.intersection(idx2))\n"
    "        union = len(idx1.union(idx2))\n"
    "        jaccard_matrix[i, j] = intersection / union if union > 0 else 0.0\n"
    "\n"
    "df_jaccard = pd.DataFrame(jaccard_matrix, index=[m.upper() for m in METHODS], columns=[m.upper() for m in METHODS])\n"
    "print(f'Jaccard Overlap of Top-{best_n} Feature Sets:')\n"
    "print(df_jaccard.to_string())\n"
    "\n"
    "plt.figure(figsize=(6, 5))\n"
    "sns.heatmap(df_jaccard, annot=True, cmap='Blues', fmt='.2f', vmin=0, vmax=1, cbar_kws={'label': 'Jaccard Index'})\n"
    "plt.title(f'Jaccard Overlap of Top-{best_n} Feature Sets', fontsize=11)\n"
    "plt.tight_layout()\n"
    "jacc_path = os.path.join(FIGURES_DIR, '07_jaccard_overlap.png')\n"
    "plt.savefig(jacc_path, dpi=120)\n"
    "plt.close()\n"
    "print(f'Jaccard heatmap saved -> {jacc_path}')\n"
))

# ── Cell 7: Correlation Heatmap ──────────────────────────────────────────────
cells.append(new_markdown_cell("## Section 6 — Chosen Feature Set: Correlation Heatmap"))

cells.append(new_code_cell(
    "best_indices, best_names = feature_selections[best_method][best_n]\n"
    "df_corr = pd.DataFrame(X_tr[:, best_indices], columns=best_names)\n"
    "corr_matrix = df_corr.corr().abs()\n"
    "\n"
    "plt.figure(figsize=(10, 8))\n"
    "sns.heatmap(corr_matrix, cmap='Oranges', vmin=0, vmax=1,\n"
    "            xticklabels=best_names, yticklabels=best_names, cbar_kws={'label': 'Absolute Correlation'})\n"
    "plt.title(f'Feature Correlation Heatmap ({best_method.upper()}, n={best_n})', fontsize=12)\n"
    "\n"
    "# Highlight high-correlation pairs (|r| > 0.8) with small markers or prints\n"
    "print('High correlation pairs (|r| > 0.8) in chosen set:')\n"
    "high_corr_found = False\n"
    "for i in range(len(best_names)):\n"
    "    for j in range(i+1, len(best_names)):\n"
    "        r_val = corr_matrix.iloc[i, j]\n"
    "        if r_val > 0.8:\n"
    "            print(f'  {best_names[i]} <-> {best_names[j]} : {r_val:.3f}')\n"
    "            high_corr_found = True\n"
    "if not high_corr_found:\n"
    "    print('  None found! Features are highly independent.')\n"
    "\n"
    "plt.tight_layout()\n"
    "corr_path = os.path.join(FIGURES_DIR, '07_feature_correlation.png')\n"
    "plt.savefig(corr_path, dpi=120)\n"
    "plt.close()\n"
    "print(f'Correlation heatmap saved -> {corr_path}')\n"
))

# ── Cell 8: Feature Group Contribution ───────────────────────────────────────
cells.append(new_markdown_cell("## Section 7 — Feature Group Contribution"))

cells.append(new_code_cell(
    "FEATURE_GROUPS = {\n"
    "    'OD (3)':             list(range(0, 3)),\n"
    "    'Color stats (54)':   list(range(3, 57)),\n"
    "    'LBP (3)':            list(range(57, 60)),\n"
    "    'Gabor (12)':         list(range(60, 72)),\n"
    "    'Gradient (5)':       list(range(72, 77)),\n"
    "    'Struct tensor (3)':  list(range(77, 80)),\n"
    "    'DoG (3)':            list(range(80, 83)),\n"
    "    'Superpixel (2)':     list(range(83, 85)),\n"
    "    'Entropy (1)':        [85],\n"
    "    'Edge dist (1)':      [86],\n"
    "    'GLCM (6)':           list(range(87, 93)),\n"
    "}\n"
    "\n"
    "group_counts = {}\n"
    "for idx in best_indices:\n"
    "    found_group = 'Unknown'\n"
    "    for grp_name, indices_list in FEATURE_GROUPS.items():\n"
    "        if idx in indices_list:\n"
    "            found_group = grp_name\n"
    "            break\n"
    "    group_counts[found_group] = group_counts.get(found_group, 0) + 1\n"
    "\n"
    "labels = list(group_counts.keys())\n"
    "counts = list(group_counts.values())\n"
    "\n"
    "plt.figure(figsize=(7, 7))\n"
    "plt.pie(counts, labels=labels, autopct='%1.0f%%', startangle=140, colors=sns.color_palette('pastel', len(labels)))\n"
    "plt.title(f'Feature Group Contribution (Top-{best_n} {best_method.upper()} features)', fontsize=11)\n"
    "\n"
    "pie_path = os.path.join(FIGURES_DIR, '07_group_contribution.png')\n"
    "plt.savefig(pie_path, dpi=120, bbox_inches='tight')\n"
    "plt.close()\n"
    "print(f'Pie chart saved -> {pie_path}')\n"
))

# ── Cell 9: Decision & Persistence ───────────────────────────────────────────
cells.append(new_markdown_cell("## Section 8 — Decision & Save Selected Features"))

cells.append(new_code_cell(
    "print('FEATURE SELECTION DECISION')\n"
    "print(f'  Winner method: {best_method}')\n"
    "print(f'  Chosen n: {best_n}')\n"
    "print(f'  Validation macro-F1: {best_score:.4f}')\n"
    "print(f'  Full 93 baseline F1: {baseline_f1:.4f}')\n"
    "\n"
    "print('Saving selected features to JSON + CSV in data/models...')\n"
    "out_paths = save_selected_features(\n"
    "    indices=best_indices,\n"
    "    names=best_names,\n"
    "    method=best_method,\n"
    "    n=best_n,\n"
    "    out_dir=os.path.join(PROJECT_ROOT, 'data', 'models')\n"
    ")\n"
    "\n"
    "# Update DECISION.md\n"
    "with open(decision_md_path, 'r') as fh:\n"
    "    content = fh.read()\n"
    "\n"
    "table_rows = ''\n"
    "for n in N_VALUES:\n"
    "    mrmr_f1  = df_sweep[(df_sweep['method']=='mrmr')  & (df_sweep['n']==n)]['macro_f1'].values[0]\n"
    "    anova_f1 = df_sweep[(df_sweep['method']=='anova') & (df_sweep['n']==n)]['macro_f1'].values[0]\n"
    "    rfe_f1   = df_sweep[(df_sweep['method']=='rfe')   & (df_sweep['n']==n)]['macro_f1'].values[0]\n"
    "    \n"
    "    if n == 10:\n"
    "        delta_str = '—'\n"
    "    else:\n"
    "        # Delta of winning method from n-5\n"
    "        prev_f1 = df_sweep[(df_sweep['method'] == best_method) & (df_sweep['n'] == n-5)]['macro_f1'].values[0]\n"
    "        curr_f1 = df_sweep[(df_sweep['method'] == best_method) & (df_sweep['n'] == n)]['macro_f1'].values[0]\n"
    "        delta_str = f'{curr_f1 - prev_f1:+.4f}'\n"
    "        \n"
    "    mrmr_str  = f'**{mrmr_f1:.4f}**'  if best_method == 'mrmr'  and n == best_n else f'{mrmr_f1:.4f}'\n"
    "    anova_str = f'**{anova_f1:.4f}**' if best_method == 'anova' and n == best_n else f'{anova_f1:.4f}'\n"
    "    rfe_str   = f'**{rfe_f1:.4f}**'   if best_method == 'rfe'   and n == best_n else f'{rfe_f1:.4f}'\n"
    "    \n"
    "    table_rows += f'| {n} | {mrmr_str} | {anova_str} | {rfe_str} | {delta_str} |\\n'\n"
    "\n"
    "new_table = (\n"
    "    '| n  | mRMR F1 | ANOVA F1 | RFE F1 | Delta from n-5 |\\n'\n"
    "    '|----|---------|---------|--------|----------------|\\n'\n"
    "    + table_rows.rstrip('\\n')\n"
    ")\n"
    "\n"
    "# Replace feature sweep table block\n"
    "old_table_pattern = r'(\\*\\*Rule:\\*\\*.*?\\n\\n)\\| n  \\| mRMR.*?(?=\\n\\n)'\n"
    "replacement_block = r'\\g<1>' + new_table\n"
    "content = re.sub(old_table_pattern, replacement_block, content, flags=re.DOTALL)\n"
    "\n"
    "# Replace status line\n"
    "content = content.replace(\n"
    "    '**Status:** PENDING — to be filled after `notebooks/07_inspect_feature_selection.ipynb` runs.',\n"
    "    '**Status:** CONFIRMED — filled by `notebooks/07_inspect_feature_selection.ipynb`.'\n"
    ")\n"
    "\n"
    "# Replace final choice placeholders\n"
    "content = content.replace(\n"
    "    '**Final n:** `[TO BE FILLED BY NOTEBOOK]`',\n"
    "    f'**Final n:** `{best_n}`'\n"
    ")\n"
    "content = content.replace(\n"
    "    '**Final method:** `[TO BE FILLED BY NOTEBOOK]`',\n"
    "    f'**Final method:** `{best_method}`'\n"
    ")\n"
    "\n"
    "with open(decision_md_path, 'w') as fh:\n"
    "    fh.write(content)\n"
    "\n"
    "print(f'DECISION.md updated successfully at: {decision_md_path}')\n"
    "# Print Decision 2 section\n"
    "lines = content.split('\\n')\n"
    "in_d2 = False\n"
    "for line in lines:\n"
    "    if '## Decision 2' in line:\n"
    "        in_d2 = True\n"
    "    if in_d2:\n"
    "        print(line)\n"
    "\n"
    "# Write a results json\n"
    "fs_results = {\n"
    "    'winner_method': best_method,\n"
    "    'chosen_n': best_n,\n"
    "    'validation_macro_f1': best_score,\n"
    "    'baseline_93_f1': baseline_f1,\n"
    "    'sweep_results': sweep_results,\n"
    "    'out_paths': out_paths,\n"
    "}\n"
    "fs_results_path = os.path.join(PHASE_DIR, 'feature_selection_results.json')\n"
    "with open(fs_results_path, 'w') as fh:\n"
    "    json.dump(fs_results, fh, indent=2)\n"
    "print(f'feature_selection_results.json written -> {fs_results_path}')\n"
))

# ── Build and write the notebook ──────────────────────────────────────────────
nb = new_notebook(cells=cells)
nb.metadata.update({
    "kernelspec": {
        "display_name": "Python 3",
        "language": "python",
        "name": "python3",
    },
    "language_info": {
        "name": "python",
        "version": "3.11.0",
    }
})

out_path = os.path.join(os.path.dirname(os.path.abspath(__file__)), '07_inspect_feature_selection.ipynb')
with open(out_path, 'w') as fh:
    nbformat.write(nb, fh)

print(f"Notebook written: {out_path}")
