import numpy as np
from skimage.morphology import binary_erosion, disk


def generate_binary_labels(mask):
	"""
	Generate binary segmentation labels from PanNuke instance mask.

	Parameters
	----------
	mask : np.ndarray, shape (256, 256, 6)
		PanNuke mask tensor. Channels 0-4 are nucleus types,
		channel 5 is background. Each channel contains unique
		integer IDs per nucleus instance, 0 elsewhere.

	Returns
	-------
	labels : np.ndarray, shape (256, 256), dtype uint8
		0 = background, 1 = nucleus (any type)
	"""
	nucleus_binary = (mask[:, :, :5].sum(axis=2) > 0).astype(np.uint8)

	assert nucleus_binary.shape == (256, 256)
	assert nucleus_binary.dtype == np.uint8
	assert set(np.unique(nucleus_binary)).issubset({0, 1})

	return nucleus_binary


def generate_3class_labels(mask, erosion_radius=2):
	"""
	Generate 3-class segmentation labels with explicit boundary class.

	Classes: 0=background, 1=nucleus interior, 2=nucleus boundary

	Boundary is generated by eroding EACH nucleus individually, then
	subtracting the eroded mask from the original binary mask.
	Eroding individually prevents touching nuclei from sharing boundaries.

	Parameters
	----------
	mask : np.ndarray, shape (256, 256, 6)
	erosion_radius : int
		Radius of disk structuring element for erosion.

	Returns
	-------
	labels : np.ndarray, shape (256, 256), dtype uint8
		0=background, 1=nucleus interior, 2=nucleus boundary
	"""
	selem = disk(erosion_radius)

	nucleus_binary = (mask[:, :, :5].sum(axis=2) > 0)

	eroded = np.zeros((256, 256), dtype=bool)

	for c in range(5):
		channel = mask[:, :, c]
		instance_ids = np.unique(channel)
		instance_ids = instance_ids[instance_ids > 0]

		for inst_id in instance_ids:
			single_nucleus = (channel == inst_id)
			eroded_nucleus = binary_erosion(single_nucleus, selem)
			eroded |= eroded_nucleus

	boundary = nucleus_binary & (~eroded)

	labels = np.zeros((256, 256), dtype=np.uint8)
	labels[eroded] = 1
	labels[boundary] = 2

	assert labels.max() <= 2
	assert labels.min() >= 0
	assert (boundary & ~nucleus_binary).sum() == 0

	return labels


def extract_nucleus_instances(image, mask):
	"""
	Extract all nucleus instances from one image for Stage 2 training.

	Parameters
	----------
	image : np.ndarray, shape (256, 256, 3) -- RGB, float32 0-255
	mask  : np.ndarray, shape (256, 256, 6)

	Returns
	-------
	list of dicts, one per nucleus instance:
		{
		  'class': int (0-4),
		  'class_name': str,
		  'region_mask': np.ndarray (256,256) bool -- True at nucleus pixels,
		  'bbox': (min_row, min_col, max_row, max_col),
		  'image': np.ndarray (256,256,3) -- full image for context
		}
	"""
	class_names = [
		'neoplastic',
		'inflammatory',
		'connective',
		'dead',
		'epithelial',
	]
	instances = []

	for class_idx in range(5):
		channel = mask[:, :, class_idx]
		inst_ids = np.unique(channel)
		inst_ids = inst_ids[inst_ids > 0]

		for inst_id in inst_ids:
			region = (channel == inst_id)
			area = region.sum()

			if area < 10:
				continue

			rows = np.where(region.any(axis=1))[0]
			cols = np.where(region.any(axis=0))[0]
			bbox = (rows[0], cols[0], rows[-1] + 1, cols[-1] + 1)

			instances.append({
				'class': class_idx,
				'class_name': class_names[class_idx],
				'region_mask': region,
				'bbox': bbox,
				'image': image,
			})

	return instances
